# Generated by Django 5.2.7 on 2026-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('commit_message', models.TextField()),
                ('modified_files', models.JSONField(default=list)),
                ('generated_readme', models.TextField(blank=True)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
