# Generated by Django 5.2.7 on 2026-06-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushevent',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='template',
            field=models.CharField(choices=[('simple', 'Simple'), ('opensource', 'Open Source'), ('professional', 'Professional')], default='simple', max_length=20),
        ),
    ]
