# Generated by Django 5.2.7 on 2026-06-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_pushevent_suggestions_pushevent_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(max_length=255, unique=True)),
                ('repo_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=255, unique=True)),
                ('github_user_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('public_repos', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pushevent',
            options={'ordering': ['-pushed_at']},
        ),
        migrations.AddField(
            model_name='pushevent',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='previous_readme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_events', to='webhook.repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='webhook.user'),
        ),
        migrations.AddField(
            model_name='pushevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_events', to='webhook.user'),
        ),
    ]
