# Generated by Django 5.2.7 on 2026-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_repository_user_alter_pushevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=255, unique=True)),
                ('template', models.CharField(choices=[('simple', 'Simple'), ('opensource', 'Open Source'), ('professional', 'Professional')], default='simple', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='pushevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='commit_sha',
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='previous_readme',
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pushevent',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
